//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduktSoftFrontEnd.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server/", ConfigurationName="Service.Servicio")]
    public interface Servicio {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Servicio/validarLoginRequest", ReplyAction="http://server/Servicio/validarLoginResponse")]
        EduktSoftFrontEnd.Service.validarLoginResponse validarLogin(EduktSoftFrontEnd.Service.validarLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Servicio/validarLoginRequest", ReplyAction="http://server/Servicio/validarLoginResponse")]
        System.Threading.Tasks.Task<EduktSoftFrontEnd.Service.validarLoginResponse> validarLoginAsync(EduktSoftFrontEnd.Service.validarLoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Servicio/helloRequest", ReplyAction="http://server/Servicio/helloResponse")]
        EduktSoftFrontEnd.Service.helloResponse hello(EduktSoftFrontEnd.Service.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Servicio/helloRequest", ReplyAction="http://server/Servicio/helloResponse")]
        System.Threading.Tasks.Task<EduktSoftFrontEnd.Service.helloResponse> helloAsync(EduktSoftFrontEnd.Service.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Servicio/restaurarContraRequest", ReplyAction="http://server/Servicio/restaurarContraResponse")]
        EduktSoftFrontEnd.Service.restaurarContraResponse restaurarContra(EduktSoftFrontEnd.Service.restaurarContraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Servicio/restaurarContraRequest", ReplyAction="http://server/Servicio/restaurarContraResponse")]
        System.Threading.Tasks.Task<EduktSoftFrontEnd.Service.restaurarContraResponse> restaurarContraAsync(EduktSoftFrontEnd.Service.restaurarContraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarLogin", Namespace="http://server/", Order=0)]
        public EduktSoftFrontEnd.Service.validarLoginRequestBody Body;
        
        public validarLoginRequest() {
        }
        
        public validarLoginRequest(EduktSoftFrontEnd.Service.validarLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public validarLoginRequestBody() {
        }
        
        public validarLoginRequestBody(string nombre, string contraseña) {
            this.nombre = nombre;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarLoginResponse", Namespace="http://server/", Order=0)]
        public EduktSoftFrontEnd.Service.validarLoginResponseBody Body;
        
        public validarLoginResponse() {
        }
        
        public validarLoginResponse(EduktSoftFrontEnd.Service.validarLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public validarLoginResponseBody() {
        }
        
        public validarLoginResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://server/", Order=0)]
        public EduktSoftFrontEnd.Service.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(EduktSoftFrontEnd.Service.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://server/", Order=0)]
        public EduktSoftFrontEnd.Service.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(EduktSoftFrontEnd.Service.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class restaurarContraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="restaurarContra", Namespace="http://server/", Order=0)]
        public EduktSoftFrontEnd.Service.restaurarContraRequestBody Body;
        
        public restaurarContraRequest() {
        }
        
        public restaurarContraRequest(EduktSoftFrontEnd.Service.restaurarContraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class restaurarContraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public restaurarContraRequestBody() {
        }
        
        public restaurarContraRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class restaurarContraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="restaurarContraResponse", Namespace="http://server/", Order=0)]
        public EduktSoftFrontEnd.Service.restaurarContraResponseBody Body;
        
        public restaurarContraResponse() {
        }
        
        public restaurarContraResponse(EduktSoftFrontEnd.Service.restaurarContraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class restaurarContraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public restaurarContraResponseBody() {
        }
        
        public restaurarContraResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioChannel : EduktSoftFrontEnd.Service.Servicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<EduktSoftFrontEnd.Service.Servicio>, EduktSoftFrontEnd.Service.Servicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EduktSoftFrontEnd.Service.validarLoginResponse EduktSoftFrontEnd.Service.Servicio.validarLogin(EduktSoftFrontEnd.Service.validarLoginRequest request) {
            return base.Channel.validarLogin(request);
        }
        
        public int validarLogin(string nombre, string contraseña) {
            EduktSoftFrontEnd.Service.validarLoginRequest inValue = new EduktSoftFrontEnd.Service.validarLoginRequest();
            inValue.Body = new EduktSoftFrontEnd.Service.validarLoginRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.contraseña = contraseña;
            EduktSoftFrontEnd.Service.validarLoginResponse retVal = ((EduktSoftFrontEnd.Service.Servicio)(this)).validarLogin(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EduktSoftFrontEnd.Service.validarLoginResponse> EduktSoftFrontEnd.Service.Servicio.validarLoginAsync(EduktSoftFrontEnd.Service.validarLoginRequest request) {
            return base.Channel.validarLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<EduktSoftFrontEnd.Service.validarLoginResponse> validarLoginAsync(string nombre, string contraseña) {
            EduktSoftFrontEnd.Service.validarLoginRequest inValue = new EduktSoftFrontEnd.Service.validarLoginRequest();
            inValue.Body = new EduktSoftFrontEnd.Service.validarLoginRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.contraseña = contraseña;
            return ((EduktSoftFrontEnd.Service.Servicio)(this)).validarLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EduktSoftFrontEnd.Service.helloResponse EduktSoftFrontEnd.Service.Servicio.hello(EduktSoftFrontEnd.Service.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            EduktSoftFrontEnd.Service.helloRequest inValue = new EduktSoftFrontEnd.Service.helloRequest();
            inValue.Body = new EduktSoftFrontEnd.Service.helloRequestBody();
            inValue.Body.name = name;
            EduktSoftFrontEnd.Service.helloResponse retVal = ((EduktSoftFrontEnd.Service.Servicio)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EduktSoftFrontEnd.Service.helloResponse> EduktSoftFrontEnd.Service.Servicio.helloAsync(EduktSoftFrontEnd.Service.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<EduktSoftFrontEnd.Service.helloResponse> helloAsync(string name) {
            EduktSoftFrontEnd.Service.helloRequest inValue = new EduktSoftFrontEnd.Service.helloRequest();
            inValue.Body = new EduktSoftFrontEnd.Service.helloRequestBody();
            inValue.Body.name = name;
            return ((EduktSoftFrontEnd.Service.Servicio)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EduktSoftFrontEnd.Service.restaurarContraResponse EduktSoftFrontEnd.Service.Servicio.restaurarContra(EduktSoftFrontEnd.Service.restaurarContraRequest request) {
            return base.Channel.restaurarContra(request);
        }
        
        public int restaurarContra(string name) {
            EduktSoftFrontEnd.Service.restaurarContraRequest inValue = new EduktSoftFrontEnd.Service.restaurarContraRequest();
            inValue.Body = new EduktSoftFrontEnd.Service.restaurarContraRequestBody();
            inValue.Body.name = name;
            EduktSoftFrontEnd.Service.restaurarContraResponse retVal = ((EduktSoftFrontEnd.Service.Servicio)(this)).restaurarContra(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EduktSoftFrontEnd.Service.restaurarContraResponse> EduktSoftFrontEnd.Service.Servicio.restaurarContraAsync(EduktSoftFrontEnd.Service.restaurarContraRequest request) {
            return base.Channel.restaurarContraAsync(request);
        }
        
        public System.Threading.Tasks.Task<EduktSoftFrontEnd.Service.restaurarContraResponse> restaurarContraAsync(string name) {
            EduktSoftFrontEnd.Service.restaurarContraRequest inValue = new EduktSoftFrontEnd.Service.restaurarContraRequest();
            inValue.Body = new EduktSoftFrontEnd.Service.restaurarContraRequestBody();
            inValue.Body.name = name;
            return ((EduktSoftFrontEnd.Service.Servicio)(this)).restaurarContraAsync(inValue);
        }
    }
}
